# Generated by Django 6.0.4 on 2026-04-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="empresa",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="job",
            name="titulo",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="job",
            name="ubicacion",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
