# Generated by Django 6.0.4 on 2026-04-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_alter_job_empresa_alter_job_titulo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="url_original",
            field=models.URLField(max_length=500),
        ),
    ]
