# Generated by Django 6.0.4 on 2026-04-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_job_url_original"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoringKeyWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("termino", models.CharField(max_length=100)),
                ("peso", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="job",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
